/* LANGUAGE */
const LANGUAGE_MIN_LENGTH = 2;
const LANGUAGE_MAX_LENGTH = 3;
const LANGUAGES = ['eng', 'fr'];
const LANGUAGE_DEFAULT = 'fr';

/* LOGIN */
const TOKEN_MAX_ACCEPTED_LENGTH = 500;
const ACCESS_TOKEN_EXPIRATION = '15m';
const REFRESH_TOKEN_EXPIRATION = '1h';

/* USER */
const USER_USERNAME_MIN_LENGTH = 3;
const USER_USERNAME_MAX_LENGTH = 15;
// Regex for username (no spaces, no special chars except _ and -)
const USER_USERNAME_REGEX = new RegExp(`^[a-zA-Z0-9_-]{${USER_USERNAME_MIN_LENGTH},${USER_USERNAME_MAX_LENGTH}}$`)
const USER_PASSWORD_MIN_LENGTH = 8;
const USER_PASSWORD_MAX_LENGTH = 30;
// Regex for password (at least 8 chars, includes uppercase, lowercase, and a number, and a speciap character, no spaces)
const USER_PASSWORD_REGEX = new RegExp(`^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*])[A-Za-z\\d!@#$%^&*]{${USER_PASSWORD_MIN_LENGTH},${USER_PASSWORD_MAX_LENGTH}}$`);

/* CATEGORY */
const CATEGORY_NAME_MIN_LENGTH = 3;
const CATEGORY_NAME_MAX_LENGTH = 30;
const CATEGORY_DESCRIPTION_MIN_LENGTH = 3;
const CATEGORY_DESCRIPTION_MAX_LENGTH = 250;

/* QUESTION */
const QUESTION_QUESTIONTEXT_MIN_LENGTH = 3;
const QUESTION_QUESTIONTEXT_MAX_LENGTH = 30;
const QUESTION_MAX_OPTIONS = 4;
const QUESTION_ANSWER_MIX_LENGTH = 3;
const QUESTION_ANSWER_MAX_LENGTH = 30;
const QUESTION_EXPLANATION_MIN_LENGTH = 3;
const QUESTION_EXPLANATION_MAX_LENGTH = 250;
const QUESTION_IMAGEURL_MIN_LENGTH = 3;
const QUESTION_IMAGEURL_MAX_LENGTH = 50;


module.exports = {
  LANGUAGE_MIN_LENGTH,
  LANGUAGE_MAX_LENGTH,
  LANGUAGES,
  LANGUAGE_DEFAULT,

  TOKEN_MAX_ACCEPTED_LENGTH,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION,

  USER_USERNAME_MIN_LENGTH,
  USER_USERNAME_MAX_LENGTH,
  USER_USERNAME_REGEX,
  USER_PASSWORD_MIN_LENGTH,
  USER_PASSWORD_MAX_LENGTH,
  USER_PASSWORD_REGEX,

  CATEGORY_NAME_MIN_LENGTH,
  CATEGORY_NAME_MAX_LENGTH,
  CATEGORY_DESCRIPTION_MIN_LENGTH,
  CATEGORY_DESCRIPTION_MAX_LENGTH,

  QUESTION_QUESTIONTEXT_MIN_LENGTH,
  QUESTION_QUESTIONTEXT_MAX_LENGTH,
  QUESTION_MAX_OPTIONS,
  QUESTION_ANSWER_MIX_LENGTH,
  QUESTION_ANSWER_MAX_LENGTH,
  QUESTION_EXPLANATION_MIN_LENGTH,
  QUESTION_EXPLANATION_MAX_LENGTH,
  QUESTION_IMAGEURL_MIN_LENGTH,
  QUESTION_IMAGEURL_MAX_LENGTH
};