const MAX_PLAYERS = 4;
const ROOM_PASSWORD_MAX_LENGTH = 12;
const ROOM_PASSWORD_ALLOWED_CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*?';
const ROOM_STATUS = {
  WAITING: 0,
  OUTGOING: 1,
  UNFINISH: 2,
  COMPLETED: 3
};

module.exports = {
    MAX_PLAYERS,
    ROOM_PASSWORD_MAX_LENGTH,
    ROOM_PASSWORD_ALLOWED_CHARACTERS,
    ROOM_STATUS
};