const ROOM_PASSWORD_MAX_LENGTH = 12;
const ROOM_PASSWORD_ALLOWED_CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*?';

const ROOM_STATUS = {
  WAITING: 0,
  OUTGOING: 1,
  UNFINISH: 2,
  COMPLETED: 3
};
const ROOM_MAX_PLAYERS = 4;
const ROOM_DEFAULT_CHOOSENTIMER = 15;
const ROOM_DEFAULT_LANGUAGE = 'fr';
const ROOM_CHAT_MESSAGE_MAX_LENGTH = 25;

module.exports = {
  ROOM_PASSWORD_MAX_LENGTH,
  ROOM_PASSWORD_ALLOWED_CHARACTERS,

  ROOM_STATUS,
  ROOM_MAX_PLAYERS,
  ROOM_DEFAULT_CHOOSENTIMER,
  ROOM_DEFAULT_LANGUAGE,
  ROOM_CHAT_MESSAGE_MAX_LENGTH
};